#!/bin/sh

# AwlsomeLinux Initialization Chart:
#
# /init (this file)
#  |
#  +--(1) /etc/01_mount.sh
#          |
#          +--(2) /etc/02_init.sh
#                  |
#                  +-- /sbin/init
#                       |
#                       +--(1) /etc/03_boot.sh
#                       |       |
#                       |       +-- udhcpc
#                       |           |
#                       |           +-- /etc/rc.udhcp
#                       +--(2) /bin/login (Alt + F1, Main Login Console)
#                       |
#                       +--(2) /bin/login (Alt + F2)
#                       |
#                       +--(2) /bin/login (Alt + F3)
#                       |
#                       +--(3) /bin/sh (Alt + F4, Recovery/Debug Shell)
#                       |
#                       +--(3) /bin/login (Alt + F4 [PUBLIC RELEASES ONLY])
clear
echo -e "\e[1;7mAwlsomeLinux Initialization (Release 1.2.1)\e[0m"

# Mount Core Filesystems (InitramFS + OverlayFS)
exec /etc/01_mount.sh
echo -e "\e[1;31m(Fail) \e[0mInit Script Failed."
read -n1 -s
