#!/bin/sh

## AwlsomeLinux Initilization

##################
# InitramFS Init #
##################

initramfs_init() {
	echo "Supressing Kernel Messages..."
	dmesg -n 1
	
	echo "Mounting File System..."
	mount -t devtmpfs none /dev
	mount -t proc none /proc
	mount -t tmpfs none /tmp -o mode=1777
	mount -t sysfs none /sys
	mkdir -p /dev/pts
	mount -t devpts none /dev/pts
	echo "Mounted all File Systems."
}

initramfs_boot() {
	cat /etc/msg/initramfs_boot.txt
	

###############
# Master Init #
###############

echo -e "Booting AwlsomeLinux..."
